(function(){
  'use strict';
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  const pages=[['index.html','முகப்பு','Home'],['news.html','செய்திகள்','News'],['events.html','நிகழ்வுகள்','Events'],['campaigns.html','பிரச்சாரங்கள்','Campaigns'],['district.html','மாவட்டங்கள்','Districts'],['gallery.html','கேலரி','Gallery'],['videos.html','வீடியோக்கள்','Videos'],['members.html','உறுப்பினர்கள்','Members'],['about.html','எங்களை பற்றி','About'],['contact.html','தொடர்பு','Contact']];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast=msg=>{let t=$('#uiToast');if(!t){t=document.createElement('div');t.id='uiToast';t.className='ui-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1900);window.__dyfiToast=toast;};
  const open=d=>{if(!d)return;if(d.showModal)try{d.showModal();}catch{d.setAttribute('open','')}else d.setAttribute('open','');};
  const close=d=>{if(!d)return;try{d.close?.()}catch{}d.removeAttribute('open');};

  const I18N={
    'NAVIGATION':['NAVIGATION','வழிசெலுத்தல்'],'QUICK ACTIONS':['QUICK ACTIONS','விரைவு செயல்கள்'],'SUPPORT':['SUPPORT','உதவி'],
    'முகப்பு':['முகப்பு','Home'],'செய்திகள்':['செய்திகள்','News'],'நிகழ்வுகள்':['நிகழ்வுகள்','Events'],'பிரச்சாரங்கள்':['பிரச்சாரங்கள்','Campaigns'],'மாவட்டங்கள்':['மாவட்டங்கள்','Districts'],'கேலரி':['கேலரி','Gallery'],'வீடியோக்கள்':['வீடியோக்கள்','Videos'],'உறுப்பினர்கள்':['உறுப்பினர்கள்','Members'],'எங்களை பற்றி':['எங்களை பற்றி','About Us'],'தொடர்பு':['தொடர்பு','Contact'],
    'App-ஐ பகிர்':['App-ஐ பகிர்','Share App'],'Settings':['Settings','Settings'],'Feedback':['Feedback','Feedback'],'Report':['Report','Report'],'AI Assistant':['AI Assistant','AI Assistant'],
    'முகப்பு':['Home','முகப்பு'],'செய்திகள்':['News','செய்திகள்'],'நிகழ்வுகள்':['Events','நிகழ்வுகள்'],'பிரச்சாரங்கள்':['Campaigns','பிரச்சாரங்கள்'],'மாவட்டங்கள்':['Districts','மாவட்டங்கள்'],'கேலரி':['Gallery','கேலரி'],'வீடியோக்கள்':['Videos','வீடியோக்கள்'],'உறுப்பினர்கள்':['Members','உறுப்பினர்கள்'],'எங்களை பற்றி':['About Us','எங்களை பற்றி'],'தொடர்பு':['Contact','தொடர்பு'],
    'Share':['Share','பகிர்'],'Save':['Save','சேமி'],'Saved':['Saved','சேமிக்கப்பட்டது'],'PDF':['PDF','PDF'],'See More':['See More','மேலும் பார்க்க'],'View All':['View All','அனைத்தையும் பார்க்க'],'Search':['Search','தேடல்'],'Clear':['Clear','அழி'],'Close':['Close','மூடு'],'Cancel':['Cancel','ரத்து'],'Send':['Send','அனுப்பு'],'Send Feedback':['Send Feedback','கருத்தை அனுப்பு'],'Send Report':['Send Report','புகாரை அனுப்பு'],
    'Day / Night':['Day / Night','பகல் / இரவு'],'Notifications':['Notifications','அறிவிப்புகள்'],'App Notifications':['App Notifications','ஆப் அறிவிப்புகள்'],'Language':['Language','மொழி'],'Share App':['Share App','ஆப்பை பகிர்'],'Tamil':['Tamil','தமிழ்'],'English':['English','English'],
    'Home':['Home','முகப்பு'],'News':['News','செய்திகள்'],'Events':['Events','நிகழ்வுகள்'],'Gallery':['Gallery','கேலரி'],'Profile':['Profile','சுயவிவரம்'],'Campaigns':['Campaigns','பிரச்சாரங்கள்'],'Districts':['Districts','மாவட்டங்கள்'],'Videos':['Videos','வீடியோக்கள்'],'Members':['Members','உறுப்பினர்கள்'],'Contact':['Contact','தொடர்பு'],
    'Latest News':['Latest News','சமீபத்திய செய்திகள்'],'Latest Updates':['Latest Updates','சமீபத்திய தகவல்கள்'],'LATEST UPDATES':['LATEST UPDATES','சமீபத்திய தகவல்கள்'],'Upcoming Events':['Upcoming Events','வரவிருக்கும் நிகழ்வுகள்'],'View All':['View All','அனைத்தையும் பார்க்க'],'All Rights Reserved.':['All Rights Reserved.','அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.'],'Built for Tamil Youth • Premium Web Experience':['Built for Tamil Youth • Premium Web Experience','தமிழ் இளைஞர்களுக்காக • பிரீமியம் இணைய அனுபவம்'],
    'All':['All','அனைத்தும்'],'Photos':['Photos','புகைப்படங்கள்'],'Meetings':['Meetings','கூட்டங்கள்'],'Campaign Hub':['Campaign Hub','பிரச்சார மையம்'],'State Team':['State Team','மாநிலக் குழு'],
    'Leadership':['Leadership','தலைமை'],'Committee':['Committee','குழு'],'Total Members':['Total Members','மொத்த உறுப்பினர்கள்'],'State Leadership':['State Leadership','மாநில தலைமை'],'State Committee':['State Committee','மாநிலக் குழு'],
    'Social Links':['Social Links','சமூக வலைதள இணைப்புகள்'],'Quick Actions':['Quick Actions','விரைவு செயல்கள்'],'About':['About','பற்றி'],'Full Name':['Full Name','முழுப் பெயர்'],'Username':['Username','பயனர் பெயர்'],'Date of Birth':['Date of Birth','பிறந்த தேதி'],'Email':['Email','மின்னஞ்சல்'],'Phone':['Phone','தொலைபேசி'],
    'Contact Us':['Contact Us','தொடர்பு கொள்ளுங்கள்'],'Get in Touch':['Get in Touch','தொடர்பு கொள்ளுங்கள்'],'Send Mail':['Send Mail','மின்னஞ்சல் அனுப்பு'],'Call Now':['Call Now','அழைக்கவும்'],'Open':['Open','திறக்கவும்'],'Visit':['Visit','பார்வையிடவும்'],'Watch':['Watch','பார்க்கவும்'],
    'Welcome':['Welcome','வரவேற்பு'],'Latest Update':['Latest Update','சமீபத்திய தகவல்'],'No events found':['No events found','நிகழ்வுகள் கிடைக்கவில்லை'],'No videos found':['No videos found','வீடியோக்கள் கிடைக்கவில்லை'],'View Details':['View Details','விவரங்களை பார்க்க'],'Download':['Download','பதிவிறக்கு'],'Like':['Like','விருப்பம்'],'Load More':['Load More','மேலும் ஏற்று'],'No More Images':['No More Images','மேலும் படங்கள் இல்லை'],'Playing':['Playing','இயக்கப்படுகிறது'],'Categories':['Categories','வகைகள்'],'Retry':['Retry','மீண்டும் முயற்சி'],'Watch':['Watch','பார்க்க'],'Register Now':['Register Now','இப்போது பதிவு செய்க'],'Become a Volunteer':['Become a Volunteer','தன்னார்வலராக இணையுங்கள்'],'Share this news':['Share this news','இந்த செய்தியை பகிருங்கள்'],'Copy Link':['Copy Link','இணைப்பை நகலெடு'],'More':['More','மேலும்'],'Refresh':['Refresh','புதுப்பி'],'Official':['Official','அதிகாரப்பூர்வம்'],'All videos':['All videos','அனைத்து வீடியோக்கள்'],'News Update':['News Update','செய்தி புதுப்பிப்பு'],'Latest updates':['Latest updates','சமீபத்திய தகவல்கள்']
  };

  function lang(){return localStorage.getItem('dyfi_language')==='en'?'en':'ta';}
  function translateTextNode(node){
    const raw=node.nodeValue; const t=raw.trim(); if(!t||t.length>80)return;
    const hit=I18N[t]; if(!hit)return;
    const v=lang()==='en'?hit[0]:hit[1];
    if(raw.trim()!==v)node.nodeValue=raw.replace(t,v);
  }
  function translate(root=document){
    root.querySelectorAll?.('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;const pair=I18N[key];if(pair)el.textContent=lang()==='en'?pair[0]:pair[1];});
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(n.parentElement?.closest('script,style,textarea,input,select'))continue;translateTextNode(n);}
    root.querySelectorAll?.('input[placeholder],textarea[placeholder],button[aria-label],a[aria-label],img[alt]').forEach(el=>{
      const attr=el.hasAttribute('placeholder')?'placeholder':el.hasAttribute('aria-label')?'aria-label':'alt';const pair=I18N[el.getAttribute(attr)];if(pair)el.setAttribute(attr,lang()==='en'?pair[0]:pair[1]);
    });
    document.documentElement.lang=lang();
  }
  window.__dyfiTranslate=translate;

  function inject(){
    if(!$('#uiSettingsDialog'))document.body.insertAdjacentHTML('beforeend',`<dialog id="uiSettingsDialog" class="ui-settings-dialog"><div class="ui-dialog-head"><div><small>APP SETTINGS</small><h3 data-i18n="Settings">Settings</h3></div><button class="ui-close" data-ui-close="uiSettingsDialog" aria-label="Close"><i class="fas fa-xmark"></i></button></div><div class="ui-dialog-body"><div class="ui-setting"><div class="ui-setting-icon"><i class="fas fa-circle-half-stroke"></i></div><div class="ui-setting-copy"><strong data-i18n="Day / Night">Day / Night</strong><span>தோற்றத்தை மாற்றுங்கள்</span></div><label class="ui-switch"><input id="uiTheme" type="checkbox"><span></span></label></div><div class="ui-setting"><div class="ui-setting-icon"><i class="fas fa-bell"></i></div><div class="ui-setting-copy"><strong data-i18n="Notifications">Notifications</strong><span data-i18n="App Notifications">புதிய updates பெறுங்கள்</span></div><label class="ui-switch"><input id="uiNotify" type="checkbox"><span></span></label></div><div class="ui-setting ui-language-row"><div class="ui-setting-icon"><i class="fas fa-globe"></i></div><div class="ui-setting-copy"><strong data-i18n="Language">Language</strong><span>Tamil / English</span></div><div class="lang-pills"><button type="button" class="ui-lang-btn" data-lang="ta">தமிழ்</button><button type="button" class="ui-lang-btn" data-lang="en">English</button></div></div><button class="ui-setting ui-setting-button" id="uiShareApp"><div class="ui-setting-icon"><i class="fas fa-share-nodes"></i></div><div class="ui-setting-copy"><strong data-i18n="Share App">Share App</strong><span>இந்த webapp link-ஐ பகிருங்கள்</span></div><i class="fas fa-chevron-right"></i></button></div></dialog>`);
    if(!$('#uiSearchDialog'))document.body.insertAdjacentHTML('beforeend',`<dialog id="uiSearchDialog" class="ui-search-dialog"><div class="ui-dialog-head"><div><small>SEARCH</small><h3 data-i18n="Search">தேடல்</h3></div><button class="ui-close" data-ui-close="uiSearchDialog" aria-label="Close"><i class="fas fa-xmark"></i></button></div><div class="ui-dialog-body"><input id="uiSearchInput" class="ui-search-input" type="search" placeholder="இந்த பக்கத்தில் தேடுங்கள்..." autocomplete="off"><div id="uiSearchResults" class="ui-search-results"></div></div></dialog>`);
    if(!$('#uiFeedbackDialog'))document.body.insertAdjacentHTML('beforeend',formDialog('Feedback','உங்கள் கருத்தை எங்களிடம் பகிருங்கள்','uiFeedbackDialog','uiFeedbackForm','Feedback'));
    if(!$('#uiReportDialog'))document.body.insertAdjacentHTML('beforeend',formDialog('Report','பிரச்சினையை தெளிவாக தெரிவிக்கவும்','uiReportDialog','uiReportForm','Report'));
    if(!$('#uiAiDialog'))document.body.insertAdjacentHTML('beforeend',`<dialog id="uiAiDialog" class="ui-ai-dialog"><div class="ui-dialog-head"><div><small>AI ASSISTANT</small><h3>DYFI AI Assistant</h3><p>Dialogflow connected assistant</p></div><button class="ui-close" data-ui-close="uiAiDialog" aria-label="Close"><i class="fas fa-xmark"></i></button></div><div class="ui-ai-body"><div class="ui-quick"><button type="button" data-q="News எப்படி பார்க்கலாம்?">News</button><button type="button" data-q="Events எங்கே?">Events</button><button type="button" data-q="District list எங்கே?">Districts</button><button type="button" data-q="Feedback எப்படி அனுப்புவது?">Feedback</button><button type="button" data-q="Report எப்படி செய்வது?">Report</button></div><div id="uiChatMessages" class="ui-chat-messages" aria-live="polite"></div><form id="uiChatForm" class="ui-chat-form"><textarea id="uiChatInput" class="ui-chat-input" rows="1" placeholder="Message..." autocomplete="off"></textarea><button class="ui-chat-send" type="submit" aria-label="Send"><i class="fas fa-paper-plane"></i></button></form></div></dialog>`);
  }
  function formDialog(title,desc,id,formId,type){return `<dialog id="${id}" class="ui-form-dialog"><div class="ui-dialog-head"><div><small>${type.toUpperCase()}</small><h3>${title}</h3><p>${desc}</p></div><button class="ui-close" data-ui-close="${id}" aria-label="Close"><i class="fas fa-xmark"></i></button></div><div class="ui-dialog-body"><form id="${formId}" class="ui-form"><div class="ui-field"><label>Name *</label><input name="name" required placeholder="உங்கள் பெயர்"></div><div class="ui-field"><label>Email / Phone</label><input name="contact" placeholder="தொடர்பு விவரம்"></div>${type==='Report'?'<div class="ui-field"><label>Issue *</label><input name="issue" required placeholder="எந்த பிரச்சினை ஏற்பட்டது?"></div>':'<div class="ui-field"><label>Subject *</label><input name="subject" required placeholder="Feedback subject"></div>'}<div class="ui-field"><label>Message *</label><textarea name="message" required placeholder="விவரமாக எழுதுங்கள்..."></textarea></div><div class="ui-actions"><button type="button" class="ui-btn" data-ui-close="${id}" data-i18n="Cancel">Cancel</button><button class="ui-btn primary" type="submit">${type==='Report'?'Send Report':'Send Feedback'}</button></div></form></div></dialog>`;}

  function headers(){
    if(page==='index.html')return;
    $$('.topbar,.page-header').forEach(h=>{if($('.ui-header-actions',h)||$('.header-actions',h)||h.classList.contains('news-topbar'))return;const box=document.createElement('div');box.className='ui-header-actions';box.innerHTML='<button class="ui-header-btn" data-ui-search aria-label="Search"><i class="fas fa-search"></i></button><button class="ui-header-btn" data-ui-settings aria-label="Settings"><i class="fas fa-gear"></i></button>';h.appendChild(box);});
  }

  function search(){const input=$('#uiSearchInput'),results=$('#uiSearchResults');if(!input||!results)return;const render=()=>{const q=input.value.trim().toLowerCase();const local=[];$$('main article, main section, .card, .news-card, .event-card, .campaign-card, .gallery-card, .video-card, .member-card, .dist-card, .contact-card, .about-card').forEach(el=>{const txt=(el.innerText||'').replace(/\s+/g,' ').trim();if(txt&&(!q||txt.toLowerCase().includes(q)))local.push({el,txt})});const nav=pages.filter(p=>!q||(p[0]+' '+p[1]+' '+p[2]).toLowerCase().includes(q));results.innerHTML=(local.slice(0,14).map(({el,txt})=>`<button class="ui-search-result" type="button" data-target-id="${esc(el.id||'')}"><strong>${esc(el.querySelector('h1,h2,h3,h4')?.textContent||txt.slice(0,80))}</strong><span>${esc(txt.slice(0,150))}</span></button>`).join('')||(!nav.length?'<div class="ui-search-result"><strong>தகவல் இல்லை</strong><span>வேறு keyword முயற்சி செய்யுங்கள்.</span></div>':''))+nav.map(p=>`<a class="ui-search-result" href="${p[0]}"><strong>${lang()==='en'?p[2]:p[1]}</strong><span>Page</span></a>`).join('');$$('[data-target-id]',results).forEach(b=>b.onclick=()=>{const id=b.dataset.targetId;if(id&&$('#'+CSS.escape(id))){$('#'+CSS.escape(id)).scrollIntoView({behavior:'smooth',block:'center'});close($('#uiSearchDialog'));}})};input.addEventListener('input',render);render();}

  async function shareApp(){const data={title:'DYFI Tamil Nadu State Committee',text:'DYFI Tamil Nadu State Committee web application',url:new URL('index.html',location.href).href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard?.writeText(data.url);toast(lang()==='en'?'App link copied ✓':'ஆப் இணைப்பு copy செய்யப்பட்டது ✓');}}catch{}}
  window.__dyfiShareApp=shareApp;

  async function loadPDF(){if(window.html2canvas&&window.jspdf)return true;await new Promise((resolve,reject)=>{if(!document.querySelector('script[data-pdf-lib]')){const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js';s.async=true;s.dataset.pdfLib='1';s.onload=resolve;s.onerror=reject;document.head.appendChild(s);}else resolve();});await new Promise((resolve,reject)=>{if(window.jspdf)return resolve();const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';s.async=true;s.dataset.pdfLib='2';s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});return true;}
  window.__dyfiPDF=async function(item){try{toast(lang()==='en'?'Preparing PDF...':'PDF தயாராகிறது...');await loadPDF();const wrap=document.createElement('div');wrap.className='ui-pdf-sheet';wrap.innerHTML=`<div class="pdf-brand">DYFI TAMILNADU STATE COMMITTEE <span>OFFICIAL WEB APP</span></div><h1>${esc(item.title||'Content')}</h1><div class="pdf-meta">${esc(item.meta||item.date||new Date().toLocaleDateString())}</div>${item.image?`<img src="${esc(item.image)}" crossorigin="anonymous">`:''}<p>${esc(item.body||item.desc||item.text||'')}</p><p>${esc(item.extra||item.place||'')}</p><div class="pdf-foot">DYFI Tamil Nadu State Committee • ${new Date().toLocaleString()}</div>`;document.body.appendChild(wrap);await new Promise(r=>setTimeout(r,350));const canvas=await html2canvas(wrap,{scale:2,useCORS:true,allowTaint:false,backgroundColor:'#fff'});const {jsPDF}=window.jspdf;const pdf=new jsPDF({unit:'mm',format:'a4',compress:true});const w=190,h=canvas.height*w/canvas.width;let remaining=h;const data=canvas.toDataURL('image/jpeg',.95);pdf.addImage(data,'JPEG',10,10,w,h,'','FAST');remaining-=277;while(remaining>0){pdf.addPage();pdf.addImage(data,'JPEG',10,10-(h-remaining),w,h,'','FAST');remaining-=277;}pdf.save((item.title||'document').replace(/[<>:"/\\|?*]/g,'').slice(0,70)+'.pdf');wrap.remove();toast(lang()==='en'?'PDF downloaded ✓':'PDF பதிவிறக்கம் செய்யப்பட்டது ✓');}catch(e){console.error(e);toast(lang()==='en'?'PDF could not be created':'PDF உருவாக்க முடியவில்லை');}};

  function genericActions(){
    const selectors=['.event-card','.campaign-card','.gallery-card','.dist-card','.contact-card','.about-card'];
    const enhance=()=>{$$(selectors.join(',')).forEach(card=>{const title=card.querySelector('h3,.card-title,.name')?.textContent?.trim()||'Content';const text=(card.innerText||'').replace(/\s+/g,' ').trim();const img=card.querySelector('img');card.dataset.globalTitle=title;card.dataset.globalText=text;if(img)card.dataset.globalImage=img.currentSrc||img.src;let actions=card.querySelector('.action-row');if(!actions){actions=document.createElement('div');actions.className='global-card-actions';card.appendChild(actions);}else actions.classList.add('global-card-actions');if(!actions.querySelector('[data-card-share]')){const b=document.createElement('button');b.type='button';b.dataset.cardShare='';b.className='global-mini-action';b.innerHTML='<i class="fas fa-share-nodes"></i><span data-i18n="Share">Share</span>';actions.appendChild(b);}if(!actions.querySelector('[data-card-pdf]')){const b=document.createElement('button');b.type='button';b.dataset.cardPdf='';b.className='global-mini-action';b.innerHTML='<i class="far fa-file-pdf"></i><span data-i18n="PDF">PDF</span>';actions.appendChild(b);}if(!actions.querySelector('[data-card-save]')){const b=document.createElement('button');b.type='button';b.dataset.cardSave='';b.className='global-mini-action';b.innerHTML='<i class="far fa-bookmark"></i><span data-i18n="Save">Save</span>';actions.appendChild(b);}});};enhance();translate();}

  function cardActions(){document.addEventListener('click',async e=>{const b=e.target.closest('[data-card-share],[data-card-pdf],[data-card-save]');if(!b)return;e.stopPropagation();const c=b.closest('.event-card,.campaign-card,.gallery-card,.dist-card,.contact-card,.about-card');if(!c)return;const title=c.dataset.globalTitle||'Content',text=c.dataset.globalText||title,image=c.dataset.globalImage||'';if(b.hasAttribute('data-card-share')){const url=location.href.split('#')[0]+'#'+encodeURIComponent(title);try{if(navigator.share)await navigator.share({title,text,url});else{await navigator.clipboard?.writeText(url);toast('Link copied ✓')}}catch{}}else if(b.hasAttribute('data-card-pdf'))window.__dyfiPDF?.({title,text,body:text,image,meta:page.replace('.html','')});else{const key='dyfi_saved_cards';const set=new Set(JSON.parse(localStorage.getItem(key)||'[]'));set.has(page+'|'+title)?set.delete(page+'|'+title):set.add(page+'|'+title);localStorage.setItem(key,JSON.stringify([...set]));b.classList.toggle('saved',set.has(page+'|'+title));b.querySelector('i').className=set.has(page+'|'+title)?'fas fa-bookmark':'far fa-bookmark';toast(set.has(page+'|'+title)?'Saved ✓':'Removed from saved');}});}

  function chatFallback(){const box=$('#uiChatMessages'),input=$('#uiChatInput'),form=$('#uiChatForm');if(!box||!input||!form)return;if(!box.children.length){const m=document.createElement('div');m.className='ui-msg bot';m.textContent='வணக்கம்! Dialogflow AI Assistant தொடங்க தயாராக உள்ளது. கீழே கேள்வியை உள்ளிடுங்கள்.';box.appendChild(m);}const add=(who,text)=>{const m=document.createElement('div');m.className='ui-msg '+who;m.textContent=text;box.appendChild(m);requestAnimationFrame(()=>box.scrollTop=box.scrollHeight);};const reply=t=>{const x=t.toLowerCase();if(/news|செய்தி/.test(x))return 'News page-ல் complete news, search, share, save, See More மற்றும் PDF options உள்ளன.';if(/event|நிகழ்வு/.test(x))return 'Events page-ல் நிகழ்வுகளின் image மற்றும் full details பார்க்கலாம்.';if(/district|மாவட்ட/.test(x))return 'Districts page-ல் அனைத்து மாவட்டங்களையும் பார்க்கலாம்.';if(/feedback|கருத்து/.test(x))return 'Main sidebar → Feedback திறந்து form-ஐ அனுப்புங்கள்.';if(/report|பிரச்சினை|bug/.test(x))return 'Main sidebar → Report திறந்து issue details-ஐ அனுப்புங்கள்.';return 'News, Events, Districts, Feedback அல்லது Report பற்றி கேளுங்கள்.';};const send=()=>{const t=input.value.trim();if(!t)return;add('user',t);input.value='';input.style.height='44px';setTimeout(()=>add('bot',reply(t)),180)};form.addEventListener('submit',e=>{e.preventDefault();send()});input.addEventListener('input',()=>{input.style.height='44px';input.style.height=Math.min(input.scrollHeight,110)+'px'});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$$('.ui-quick [data-q]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.q;send()}));}

  let dfLoading=false;
  async function loadDialogflow(){
    if(document.querySelector('df-messenger'))return true;
    if(!dfLoading){dfLoading=true;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1';s.async=true;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
    const el=document.createElement('df-messenger');el.setAttribute('intent','WELCOME');el.setAttribute('chat-title','DYFI - தமிழ் மாநிலக் குழு');el.setAttribute('agent-id','0ede04bf-57f2-49da-96bf-6050a3bbcbee');el.setAttribute('language-code',lang()==='en'?'en':'ta');el.id='dyfiDialogflow';document.body.appendChild(el);return true;
  }
  async function openAI(){
    try{await loadDialogflow();close($('#uiAiDialog'));toast(lang()==='en'?'Opening AI Assistant...':'AI Assistant திறக்கப்படுகிறது...');setTimeout(()=>{const df=$('#dyfiDialogflow');try{const root=df?.shadowRoot;const b=root?.querySelector('button, .df-messenger-button, .df-messenger-chat-bubble, [role="button"]');b?.click();}catch{}},800);}catch(e){console.error(e);open($('#uiAiDialog'));toast(lang()==='en'?'Dialogflow unavailable':'Dialogflow இணைப்பு கிடைக்கவில்லை');}
  }
  window.__dyfiOpenAI=openAI;

  function forms(){['uiFeedbackForm','uiReportForm'].forEach(id=>{const f=$('#'+id);if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const btn=f.querySelector('button[type=submit]');if(!btn||btn.disabled)return;const old=btn.textContent;btn.disabled=true;btn.textContent=lang()==='en'?'Sending...':'அனுப்புகிறது...';try{const fd=new FormData(f);fd.append('access_key','5e51a205-46d1-4db6-916f-0703efb327ab');fd.append('from_name','DYFI Tamil Nadu Web App');fd.append('subject',id==='uiReportForm'?'DYFI Website Report':'DYFI Website Feedback');fd.append('page',location.href);const r=await fetch('https://api.web3forms.com/submit',{method:'POST',body:fd});const d=await r.json().catch(()=>({success:r.ok}));if(!r.ok||d.success===false)throw Error('submit');f.reset();close(f.closest('dialog'));toast(lang()==='en'?'Submitted successfully ✓':'வெற்றிகரமாக அனுப்பப்பட்டது ✓');}catch(err){
        try{const data=Object.fromEntries(new FormData(f).entries());const subject=encodeURIComponent(id==='uiReportForm'?'DYFI Website Report':'DYFI Website Feedback');const body=encodeURIComponent(Object.entries(data).map(([k,v])=>`${k}: ${v}`).join('\n'));window.location.href=`mailto:info@dyfitamilnadu.org?subject=${subject}&body=${body}`;toast(lang()==='en'?'Email fallback opened':'மின்னஞ்சல் fallback திறக்கப்பட்டது');}catch{}
        toast(lang()==='en'?'Submit failed. Please try again.':'அனுப்ப முடியவில்லை. மீண்டும் முயற்சிக்கவும்.');
      }finally{btn.disabled=false;btn.textContent=old;}});});}

  function language(){
    const set=l=>{localStorage.setItem('dyfi_language',l);document.documentElement.lang=l==='en'?'en':'ta';const df=$('#dyfiDialogflow');if(df)df.setAttribute('language-code',l==='en'?'en':'ta');translate();toast(l==='en'?'English enabled ✓':'தமிழ் செயல்படுத்தப்பட்டது ✓');};
    $$('.ui-lang-btn').forEach(b=>b.addEventListener('click',()=>set(b.dataset.lang)));
    document.addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(b&&!b.closest('#uiSettingsDialog'))set(b.dataset.lang);});
  }

  function init(){
    if(window.__dyfiGlobalUIReady)return;window.__dyfiGlobalUIReady=true;
    inject();headers();search();genericActions();cardActions();chatFallback();forms();language();
    const theme=$('#uiTheme');if(theme){theme.checked=localStorage.getItem('theme')==='dark';theme.addEventListener('change',()=>{localStorage.setItem('theme',theme.checked?'dark':'light');document.documentElement.classList.toggle('dark',theme.checked);});}
    const notify=$('#uiNotify');if(notify){notify.checked=localStorage.getItem('dyfi_notifications')==='on';notify.addEventListener('change',e=>{localStorage.setItem('dyfi_notifications',e.target.checked?'on':'off');toast(e.target.checked?'Notifications enabled ✓':'Notifications disabled ✓');});}
    $('#uiShareApp')?.addEventListener('click',shareApp);
    document.addEventListener('click',e=>{const b=e.target.closest('[data-ui-search],[data-ui-settings],[data-ui-share],[data-ui-feedback],[data-ui-report],[data-ui-ai],[data-ui-close]');if(!b)return;if(b.hasAttribute('data-ui-search'))open($('#uiSearchDialog'));if(b.hasAttribute('data-ui-settings'))open($('#uiSettingsDialog'));if(b.hasAttribute('data-ui-share'))shareApp();if(b.hasAttribute('data-ui-feedback'))open($('#uiFeedbackDialog'));if(b.hasAttribute('data-ui-report'))open($('#uiReportDialog'));if(b.hasAttribute('data-ui-ai'))openAI();if(b.hasAttribute('data-ui-close'))close($('#'+b.dataset.uiClose));});
    document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('dialog[open]').forEach(close)});
    translate();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
